# Set update schedule for GitHub Actions

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "weekly"
    commit-message:
      # Prefix all commit messages with "COMP: "
      prefix: "COMP"

  - package-ecosystem: docker
    directory: /.github/actions/slicer-build
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /Modules/Scripted/WebServer/Resources/docroot
    schedule:
      interval: daily
